
DROP TABLE IF EXISTS `movie`;
CREATE TABLE IF NOT EXISTS `movie` (
    `imdb`    text NOT NULL,
    `film_nr` text NOT NULL,
    `m_title` char NOT NULL,
    `o_title` char NOT NULL,
    `time`    text NOT NULL,
    `catId`   text NOT NULL,
    `year`    text NOT NULL,
    `quality` text NOT NULL,
    `imdb_p`  real NOT NULL,
    `link`    char NOT NULL,
    `audio`   text NOT NULL,
    `srt`     text,
    `status`  int
);

INSERT INTO movie VALUES('5947416', '16KR001', 'Az utolsó hercegnő','Deokhyeongju', '2h07min', 'Akció,Életrajz,Dráma', 2016, 'HD', 7.0,'wqbUldPbzy8', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('3530418', '14KR001', 'Fejvadász csajok', 'Jo-seon-mi-nyeo-sahm-chung-sa','1h47min', 'Akció,Vígjáték', 2014, 'HD', 5.5, 'BKJEAzCOPUw', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('0762703', '09KR002', 'Szomjúság', 'Bakjwi', '2h13min', 'Dráma,Misztikus,Horror', 2009, 'HD', 7.2, 'Q3ZPtY0-bLs', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('3479208', '14KR002', 'A végzetes találkozás', 'Yeok-rin', '2h15min', 'Akció,Dráma', 2014, 'HD', 6.9, 'fDppBukzgmc', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('1846675', '10KR001', 'Natali', 'Na-tal-li', '1h30min', 'Misztikus,Romantikus', 2010, 'DVDRip', 4.6, 'T0Yj8tYpBz0', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('6589464', '17KR001', 'A börtön', 'Peurizeun', '2h05min', 'Akció,Krimi', 2017, 'HD', 6.5, 'oCwsdJrlw9s','kr','hu', 1);
INSERT INTO movie VALUES('3054798', '16KR002', 'Emlékek a kardról', 'Hyeomnyeo: Kar-ui gi-eok','2h', 'Akció,Dráma,Történelmi', 2016, 'HD', 6.3, 'G-XhnLEa9tY', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('0451094', '05KR001', 'A bosszú asszonya', 'Chinjeolhan geumjassi', '1h55min', 'Krimi,Dráma,Thriller', 2005, 'HD', 7.6, 'JfrBdXj_mac', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('6273736', '16KR003', 'Eltűnt idő: Egy fiú aki visszatért', 'Garyeojin shigan', '2h10min', 'Misztikus', 2016, 'HD', 7.3, 'N8wrPuzAJ5Q', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('1153040', '09KR001', 'Halálos szökőár', 'Haeundae', '2h', 'Akció,Vígjáték,Dráma', 2009, 'HD', 5.7, 'Gob8JjYxW6M', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('2253742', '12KR001', 'Szállj a napba', 'Al-too-bi: Riteon too beiseu', '1h53min', 'Akció,Dráma,Romantikus', 2012, 'HD', 6.1, 'NYrXUmvODRo', 'kr', 'hu', 1);
INSERT INTO movie VALUES('0341555', '02KR002', 'Semmi szex', 'Saekjeuk shigong', '1h36min', 'Vígjáték,Romantikus', 2002, 'DVDRip', 7.6, 'etaDFDA_gDE', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('0323630', '02KR001', 'Telefon', 'Pon', '1h44min', 'Dráma,Horror,Misztikus', 2002, 'DVDRip', 6.2, 'RV4hg_oR2M4', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('6777338', '17KR002', 'Bérgyilkosnő', 'Ak-Nyeo', '2h09min', 'Akció,Krimi,Thriller', 2017, 'HD', 6.7, 'K_6IDtKZwoY', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('2551894', '12KR002', '26 év', '26 nyeon', '2h15min', 'Dráma,Thriller', 2012, 'HD', 6.5, 'n_7zJYOoQwg', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('5969696', '17KR003', 'A Csatahajó-sziget','Gun-ham-do', '2h12min', 'Akció,Dráma,Misztikus', 2017, 'HD', 7.2, 'bczGmpqqqjU', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('1135972', '07KR001', 'Mesterszakács', 'Sik-gaek', '1h53min', 'Vígjáték,Dráma', 2007, 'DVDRip', 6.7, 'b5D_Xs5rg6w', 'kr', 'hu', 1);
INSERT INTO movie VALUES('1135972', '10KR002', 'Mesterszakács 2', 'Sik-gaek: Kim-chi-jeon-jaeng', '1h59min', 'Vígjáték,Dráma', 2010, 'DVDRip', 6.2, 'Ct0i4Mtay8s', 'kr', 'hu', 1);
INSERT INTO movie VALUES('4844288', '15KR001', 'Az áruló', 'Gansin', '2h13min', 'Dráma,Krimi,Történelmi', 2015, 'HD', 6.1, 'uw2gSSK4Av4', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('2557406', '11KR001', 'Az utolsó virágzás', 'Sesangyeseo Gajang Ahreumdawoon Ilbyeon', '2h05min', 'Dráma', 2011, 'DVDRip', 7.1, 'keZiOCtj2Yo', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('1905059', '10KR003', 'A cseléd', 'Bang-ja jeon', '2h05min', 'Dráma,Vígjáték,Romantikus', 2010, 'HD', 6.6, 'T_co9DEzqcM', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('4353996', '16NR001', 'A király választása', 'Kongens nei', '2h13min', 'Életrajz,Dráma,Történelmi', 2016, 'HD', 7.3, 'B4qCUOFK2yI', 'nr', 'hu', 1);
INSERT INTO movie VALUES('1615160', '17GB001', 'A külföldi', 'The foreigner', '1h53min', 'Akció.Krimi,Dráma', 2017, 'HD', 7.2, 'b3yLdUYB9eU', 'gb', 'hu', 1);
INSERT INTO movie VALUES('2558318', '00EN001', 'Az utolsó túlélő', 'The last survivors', '1h35min', 'Akció,Thriller', 2014, 'HD', 5.4, '_elWk9RRN0I', 'gb', 'hu', 1);
INSERT INTO movie VALUES('3531202', '17IR001', 'Szentév', 'Pilgrimage', '1h36min', 'Kaland,Dráma', 2017, 'HD', 5.8, '5nIc7i2wIxw', 'gb', 'ru,cs', 1);
INSERT INTO movie VALUES('1852040', '12KZ001', 'A sztyeppe harcosai', 'Zhauzhürek myng bala', '2h12min', 'Akció,Kaland,Dráma', 2012, 'HD', 6.7, 'CduX4-HYC9w', 'ru', 'hu,gb', 1);
INSERT INTO movie VALUES('0395677', '04KR001', '100 nap Beképzelt úrral', 'Nae-sa-rang ssa-ga-ji', '1h35min', 'Vígjáték,Romantikus', 2004, 'DVDRip', 6.2, 'Sd4qFfsviUE', 'kr', 'hu,ru,gb', 1);
INSERT INTO movie VALUES('5910280', '16KR004', 'Az alagút', 'Teo-neol', '2h06min', 'Akció,Dráma,Thriller', 2016, 'HD', 6.9, 'fW7PwGXBqlc', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('1979319', '12JP001', 'Rurôni Kenshin', 'Meiji kenkaku roman tan', '2h14min', 'Akció,Dráma,Történelmi', 2012, 'HD', 7.6, 'mv1T8sq0xO0', 'jp', 'hu', 1);
INSERT INTO movie VALUES('0251433', '00KR001', 'Végső leszámolás', 'Shun liu ni liu', '1h35min', 'Akció,Krimi,Dráma', 2000, 'DVDRip', 6.9, 'nLHM1XQKROU', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('1230385', '10KR004', 'A Sárga-tenger', 'Hwanghae ', '2h37min', 'Akció,Krimi,Thriller', 2010, 'HD', 7.4, 'tjLKkY6OX0c', 'kr', 'hu', 1);
INSERT INTO movie VALUES('1314652', '10KR005', 'A szobalány', 'Hanyo', '1h46min', 'Dráma,Thriller', 2010, 'HD', 6.5, 'tjLKkY6OX0c', 'kr', 'hu', 1);
INSERT INTO movie VALUES('6357806', '14KR003', 'Siratólány', 'The Crying Woman', '1h18min', 'Dráma,Történelmi', 2014, 'DVD', 9.0, 'U5t6vETFg6c', 'kr', 'hu', 1);
INSERT INTO movie VALUES('4024104', '14KR004', 'A királyi szabó', 'Sang-eui-won', '2h07min', 'Dráma,Történelmi', 2014, 'HD', 7.0, '0XEKKN2ju_M', 'kr', 'hu', 1);
INSERT INTO movie VALUES('4471636', '15KR002', 'A Csoszuni mágus', 'Chosun Masoolsa', '2h02min', 'Vígjáték,Akció,Misztikus', 2015, 'HD', 6.1, 'WuK4wsojeu8', 'kr', 'hu', 1);
INSERT INTO movie VALUES('4320560', '15KR003', 'Hosszú még az út hazáig', 'Seoboojeonsun', '1h52min', 'Akció,Dráma,Vígjáték', 2015, 'DVDRip', 6.5, '7ndMqRBP42E', 'kr', 'hu,ru,gb', 1);
INSERT INTO movie VALUES('3567666', '17NZ001', 'Stratton', 'Stratton', '1h34min', 'Akció,Thriller', 2017, 'DVDRip', 4.8, 'oCwsdJrlw9s', 'nz', 'hu', 1);
INSERT INTO movie VALUES('6690310', '17CN001', 'Különleges küldetés', 'Fei fan ren wu', '1h57min', 'Akció,Krimi', 2017, 'HD', 6.2, '2J30B7H7IyI', 'cn', 'hu,ru,gb', 1);
INSERT INTO movie VALUES('3111858', '11KR002', 'Hwapyung hercegnő', 'Hwapyung Gongjoo Chejungkamryangsa', '1h07min', 'Romantikus,Vígjáték', 2011, 'DVDRip', 4.5, 'gMNHVw0H1UU', 'kr', 'hu', 1);
INSERT INTO movie VALUES('5729246', '16KR005', 'Seondal, a folyót áruba bocsátó szélhámos', 'Bongyi Kim Seon-dal', '2h', 'Akció,Vígjáték,Történelmi', 2016, 'HD', 6.7, 'j44GVBEix1k', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('1832438', '11KR003', 'A csatamező hősei', 'Pyeong-yang-seong', '1h57min', 'Vígjáték,Dráma,Történelmi', 2011, 'DVDRip', 5.4, 'taG2WjNBluA', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('6878038', '17KR004', 'Egy taxisofőr', 'Taeksi Woonjunsa', '2h17min', 'Akció,Dráma,Történelmi', 2017, 'HD', 7.9, 'YfQ2QDGlMQc', 'kr', 'hu', 1);
INSERT INTO movie VALUES('5729246', '11KR004', 'Te vagy a háziállatom', 'Neo-neun Pet', '1h50min', 'Romantikus,Vígjáték', 2011, 'DVDRip', 5.8, 'dg1s9Y_BLBc', 'kr', 'hu,ru,gb', 1);
INSERT INTO movie VALUES('5586914', '15KR004', 'Egy szeszélyes nap', 'Keunalui bonwigi', '1h43min', 'Romantikus,Vígjáték', 2016, 'DVDRip', 6.7, 'rLGwvpN6N-E', 'kr', 'gb,ru,hu', 1);
INSERT INTO movie VALUES('0378078', '03KR001', 'Hajdan a csatamezőn', 'Hwangsanbul', '1h44min', 'Vígjáték,Dráma,Történelmi', 2003, 'DVDRip', 6.7, 'dwpQL6LS6a4', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('6434022', '16KR006', 'Ott leszel?', 'Dangshin Geogi Iteojoorraeyo', '1h51min', 'Romantikus,Fantázia,Dráma', 2016, 'HD', 7.1, '-s3bfVDbSfE', 'kr', 'hu,gb', 1);
INSERT INTO movie VALUES('3550748', '14KR005', 'Ártatlan dolog', 'Gashi', '1h57min', 'Thriller,Dráma', 2014, 'HD', 6.2, '8TJIYmy0WTc', 'kr', 'hu,ru,gb', 1);
INSERT INTO movie VALUES('2544120', '12KR003', 'A királyi ágyas', 'Hoo-goong: Je-wang-eui cheob', '2h02min', 'Romantikus,Dráma,Történelmi', 2012, 'HD', 6.1, '-2FVrVCdq94', 'kr', 'hu,gb', 1);

DROP TABLE IF EXISTS `movie_detail`;
CREATE TABLE IF NOT EXISTS `movie_detail` (
    `film_nr` text NOT NULL,
    `descrip` text NOT NULL
);

INSERT INTO movie_detail VALUES('16KR001', 'A film Kwon Bi-young 2009-ben kiadott regényéből készült és Korea utolsó hercegnőjének küzdelmes és szomorú életéről szól. A japán megszállás alatt Gojong császár legkisebb lányát Deokhyé-t Japánba küldik, hivatalosan „tanulni”, a valóságban azonban túsznak. Megpróbáltatásaival szembenézve, Deokhye azért küzd, hogy fenntartsa a koreai emberek reményét.');
INSERT INTO movie_detail VALUES('14KR001', 'Park Je-Hyun filmje a Charlie angyalai által inspirált akció/kaland vígjáték, a Csoszun dinasztia korába ágyazva. Mind humorában, mind pedig akciódússágában bátran felveszi a verseny az amerikai mozival. Igazi könnyed esti szórakozás!');
INSERT INTO movie_detail VALUES('09KR002', 'Egy kisvárosi pap története, aki egy félresikerült orvosi kísérlet nyomán vámpírrá változik, majd viszonyt kezd egy gyerekkori barátja feleségével.');
INSERT INTO movie_detail VALUES('14KR002', 'A történet 1777-ben játszódik, Jeong-jo király elleni merényletről szól, Yi San uralkodásának első évében.');
INSERT INTO movie_detail VALUES('10KR001', 'A rejtélyes melodráma három ember Jun-hyeok szobrászművész, Min-woo művészeti kritikus és a modern tánchallgató Mi-ran szerelméről és titkairól szól.');
INSERT INTO movie_detail VALUES('17KR001', 'Az egykori zsaru rács mögé kerül egy cserbenhagyásos gázolás miatt. Hősünk a börtönben azt tapasztalja, hogy az egész intézményt egy rab irányítja belülről. Valójában a börtön nem más, mint egy bűnszervezet központja, amelynek a börtönőrök is tagjai.');
INSERT INTO movie_detail VALUES('16KR002', 'A kóreai Goryo dinasztia három kiváló harcos katonája vezette a kínai Kitan törzs serege elleni támadást, ám Deok-ki elárulta népét, mely tett Poong-chun halálához vezetett. A harmadik vezérnek, Seol-rangnak sikerült elmenekülnie és magával vitte Poong kislányát is. 18 évvel később az időközben megvakult Seol-rang és nevelt lánya elérkezettnek látja az időt a bosszúhoz.');
INSERT INTO movie_detail VALUES('05KR001', 'A film veszélyes utazásra hív egy saját erkölcsi kódex szerint élő nő lelkének legmélyére. Lee Geum-ját tizenhárom év börtönre ítélték egy hatéves kisfiú elrablásának és meggyilkolásának bizonyítatlan vádja miatt. Az egyszerre gyermekien naiv és ördögien bölcs Geum-ja nem sok időt pazarol arra, hogy belopja magát a többi rab szívébe.');
INSERT INTO movie_detail VALUES('16KR003', 'Három fiú és egy lány tiltott területre lopózik egy hegyen, hogy megnézze a robbantást, amit az alagút építéséhez végeznek. Egy barlangba bújva furcsa jelenségre lesznek figyelmesek. Másnap csak a lány kerül elő. Néhány nappal később feltűnik a barátja is, aki többé nem egy 13 éves fiú, hanem egy felnőtt, akit gyermekrablással gyanúsítanak.');
INSERT INTO movie_detail VALUES('09KR001', 'Haeundae városban él Man-shik és Yeon-Hee, akik a múlt fájó emlékei miatt már abban is bizonytalanok, hogy továbbra is együtt akarnak maradni. Itt lakik a magánéleti válsággal küszködő Dr. Kim is, aki figyelmeztette a hatóságokat egy giga erejű cunami közeledésére. Itt talált otthonra Hyeong-shik és szöuli barátnője. Amikor elszabadul a pokol és lecsap a partvidékre a pusztító szökőár, mindannyiuknak küzdeni kell a túlélésért.');
INSERT INTO movie_detail VALUES('12KR001', 'Tae Hoon, a "Black Eagles" névre keresztelt elit repülős csapat tagja, ami Korea legjobb pilótáiból áll. Bajkeverő természetének köszöngetően azonban majdnem tragédiát okoz, ami miatt kiteszik őt a csapatból, így átkerül a 21-es harci egységhez.');
INSERT INTO movie_detail VALUES('02KR002', 'A film folytatja az Amerikai Pite által megkezdett tinivígjátékok sorát, amolyan ázsiai módra, csak valamivel poénosabb, és jobban kivitelezett mint előbb említett "nyugati" elődje. Könnyed - néhol azért erősen morbid humor, és jól eltalált drámai szál jellemzi. A karakterek kedvelhetőek, a történet egyszerű, de kedvelhető kis film.');
INSERT INTO movie_detail VALUES('17KR002', 'Ji-Won egy oknyomozó riporter, aki az utolsó cikke után életveszélyes fenyegetéseket kap. Emiatt egy időre elbújni kényszerül. Telefonszámot változtat és a barátainak az üresen álló lakásába húzódik vissza. Azonban az új telefonszámára is érkeznek furcsa hívások');
INSERT INTO movie_detail VALUES('02KR001', 'A történet főszereplője egy kegyetlen bérgyilkosnő, akit fiatal kora óta gyilkolásra képeztek ki. A nő ügynökként dolgozik a koreai titkosszolgálat kötelékében, azt az ígéretet tartva szem előtt, hogy tíz év szolgálat után visszavonulhat. Felbukkan azonban két férfi, és velük együtt a nő sötét múltja is.');
INSERT INTO movie_detail VALUES('12KR002', 'A történet Dél-Korea legtragikusabb eseményéhez kapcsolódik. 1980. május 18-án Gvandzsu (광주) városában az állami hadsereg parancsot kapott, hogy nyisson tüzet a tüntető civil lakosságra. Ezreket sebesítettek és öltek meg. Huszonhat évvel később, öt ember, akik magukat a mészárlás legnagyobb áldozatai közé sorolják, egy titkos tervet dolgoznak ki, hogy a felelősnek tartott ember meggyilkolásával vegyenek elégtételt.');
INSERT INTO movie_detail VALUES('17KR003', 'A film története szerint a japánok gyarmatosítási korszakának idején 400 koreait kényszerítettek rabszolgasorsba a Hashima szigeten, ahol szénbányászatra fogták őket, ám egy napon a rabok fellázadtak, és megkísérelték a szökést.');
INSERT INTO movie_detail VALUES('07KR001', 'A koreai Joseon-dinasztia (1392-1910) utolsó udvari séfe által használt speciális késért mérkőzik meg két kivételes képességű szakács, akiknek egy főzőverseny keretében kell bizonyítaniuk rátermettségüket.');
INSERT INTO movie_detail VALUES('10KR002', 'A történet azzal kezdődik, hogy Korea miniszterelnöke látogatást tesz a japán minszterelnöknél, ahol egy vacsora során vitába keverednek, hogy a kimcsi koreai, vagy japán eredetű étel. A koreai miniszterelnök hazaérkezve elhatározza, hogy a kimcsit megismerteti az egész világgal. E a cél szolgálatában nagyszabású kimcsikészítő versenyt rendeznek. A versenyre benevez Dzsangün, a hölgy aki a japán nagykövetség főszakácsa volt és mostohatestvére, Szungcsan, a mozgó zöldségárus is.');
INSERT INTO movie_detail VALUES('15KR001', ' Korea középkorában, a Csoszon-dinasztia korában, Jonszangun király volt az említett dinasztia legrosszabb uralkodója, a film szerint egyfajta távol-keleti Caligulaként kényére-kedvére tett, ami leginkább féltékenységi jeleneteket, kivégzéseket és megannyi defloreálást jelentett. Jelenlegi elfoglaltsága pedig az, hogy új ágyast keressen magának, ennek érdekében kiküldi leghűségesebb embereit, hogy fiatal lányokat gyűjtsenek be és képezzenek ki azzal az egyetlen céllal, hogy majd ölükkel kiszolgálják a királyt.Az ágyasi pozíció azonban politikai töltettel is bír, így aztán a király körül sertepertélő emberek nem bízzák a véletlenre, hogy melyik hölgy töltse majd be a pozíciót, főleg, hogy ármánykodás van születőben, az idióta királyt már régóta trónon kívül szeretné látni a nép. ');
INSERT INTO movie_detail VALUES('11KR001', 'In-hee szokványos családanya, akinek mindene a család, s látszólag minden rendben van az életével. Azonban az idilli állapot elillan, mikor kiderül, hogy gyógyíthatatlan beteg. Ez azonban csak a jéghegy csúcsa. Időközben rájön, hogy tökéletesnek hitt szerettei, közel sem olyan tökéletesek. gy In-hee, életének utolsó szakaszát annak szenteli, hogy szeretteit a helyes útra billentse, miközben állapota folyamatosan romlik és az ádáz betegséggel küzd titokban.');
INSERT INTO movie_detail VALUES('10KR003', 'Egy klasszikus történet, ami már sokszor feldolgozásra került, hát íme még egy variáció: Mong-Ryong az elöljáró fia, de közben titokban egy Robin Hood-szerű tolvajbanda tagja is. Egyik rablásuk után menekülve bemászik a legközelebbi házba, hogy elbújjon. Itt találkozik egy lánnyal, aki segít neki, és szinte szerelem lesz első látásra. Nos, szerelem az ugyan lett, de bemutatkozás az elmaradt. Így mikor Mong-Ryong elkezd áradozni a Wol-Mae asszony házában látott lányról, akkor Bang-Ja a szolgája, természetesen közli, hogy biztosan Wol-Mae asszony lánya az, Chun-Hyang. Ez a lány fülébe is eljut, így mire Mong-Ryong szembesül a ténnyel, hogy neki valójában a lány szolgálója tetszett meg, már mindenki tényként kezeli, hogy ő Chun-Hyang-ba szerelmes.');
INSERT INTO movie_detail VALUES('16NR001', '1940. április 9-én a német hadigépezet Osló előtt áll. A norvég király ultimátumot kap: megadja magát, vagy meghal. Német katonák vadásznak a királyi családra, amely arra kényszerül, hogy elhagyja a fővárost. Miközben Haakon király és Olav koronaherceg egy Elverum melletti kis farmra menekül, találkoznak a német vezetéssel. Háromnapi kemény tárgyalás után Haakon király meghozza végső döntését. Visszautasítja a kapitulációt, még ha az a saját, a családja és sok norvég életébe is kerül.');
INSERT INTO movie_detail VALUES('17GB001', 'A film főhőse egy Londonban élő bevándorló, aki bosszút esküszik, miután lánya meghal az IRA bomba támadásában.');
INSERT INTO movie_detail VALUES('00EN001', 'A tizenhét éves lány, Kendal (Haley Lu Richardson) minden erejével küzd, hogy megvédje a szárazság sújtotta völgy utolsó működő kútját a kapzsi bárótól.');
INSERT INTO movie_detail VALUES('17IR001', 'In 13th century Ireland, a group of monks must escort a sacred relic across an Irish landscape fraught with peril. ');
INSERT INTO movie_detail VALUES('12KZ001', 'Ez az akciófilmbe illő jeleneteket felvonultató történelmi dráma a XVIII sz. első felében játszódik. A kazah történelem egy kulcsfontosságú korszakában, amikor véres háború dúlt a dzsungárok ellen, a kazah nép függetlenségéért.');
INSERT INTO movie_detail VALUES('04KR001', 'Ha-yeong, miután órán egy herceggel álmodik, és barátnői szerint ez azt jelenti, hogy hamarosan az életben is találkozik vele, már alig várja, ki is lesz az. Van neki barátja, csak az meg épp szakít vele évfordulójuk előtt. Amikor hazafelé sétál, mérgében belerúg egy dobozba, ami Hyung-joon fején landol, ő pedig a kocsi műszerfalán, mikor ennek következtében nekimegy a falnak. A kocsi megsérül, Hyung-joon pedig mérges... nem jó párosítás, Ha-yeongnak esélye sincs. Pár sikertelen próbálkozás után kénytelen elfogadni Hyung-joon ajánlatát: 100 napig a fiú rabszolgája lesz. Hyung-joon beképzelt, és imád szemétkedni Ha-yeonggal, aki pedig nem kicsit makacs és élvezettel adja vissza "gazdájának" a tőle kapott "kedvességeket". ');
INSERT INTO movie_detail VALUES('16KR004', 'Egy férfi hazafelé tart, amikor a rosszul kialakított alagút összeomlik és ő benn reked az alagútban. ');
INSERT INTO movie_detail VALUES('12JP001', 'A brutális polgárháború nyomán a legendás és félelmetes gyilkos Kenshin Himura eldobja kardját, és fogadalmat tesz, hogy hátat fordítson a vérontásra. Ahelyett, hogy életét békés vándorként élte volna meg, Kenshin hamar rájön, hogy a körülötte lévő világ gyorsan változik - és nem jobb. Egy szadista kábítószer úr, Kanryu elnyomja az embereket, mérgezi meg ópiummal és ellopja azt a kevéset, amit elhagytak. Amikor ez a mohóságos szörny fenyegeti a gyönyörű Kendo oktatót, a Kenshin többé már nem tud állni. ');
INSERT INTO movie_detail VALUES('04KR001', 'Hogy megismerje jövendőbeli férje rokonait, az ifjú menyasszony a férfi szülővárosába utazik az esküvő előtt. Ott viszont a vőlegény eltűnik. A lány furcsa emberekkel találkozik, akik egy különleges szertartásra készülnek, amely teljesen morbid, melyben neki is szerepet szánnak….. ');
INSERT INTO movie_detail VALUES('17NZ001', 'John Stratton és kommandós egysége Iránban készül megrohamozni egy biológiai tömegpusztító fegyverrel kísérletező laboratóriumot, ám az akció végzetes következményekkel jár. Kiderül, hogy az akció mögött egy korábbi szovjet ügynök, Barovski (Thomas Kretschmann) áll. A férfit évek óta halottnak hitték, ám most úgy tűnik, nem hogy életben van, de harcot hirdetett egykori szervezete, sőt az egész világ ellen. de valóban tömegpusztítást tervez. Sokáig úgy tűnik, a renegát orosz mindig egy lépéssel előttük jár, a bomba pedig valahol már ketyeg...');
INSERT INTO movie_detail VALUES('00KR001', 'Tyler 21 éves hongkongi utcagyerek, akinek eddig még soha nem sikerült elnyernie mások bizalmát. Nem találja a helyét - ha tehetné azonnal repülőre szállna és letelepedne valamelyik kellemes dél-amerikai városkában - de a valóságban erre nincs sok esélye. Időközben megtudja, hogy barátnője terhes - még egy ok, ami miatt nem hagyhatja el Hongkongot. A családalapításhoz azonban pénz kell - sok pénz. Tyler testőrnek szegődik és egyik kollégájával - egy mindenből kiábrándult egykori zsoldossal, aki saját bevallása szerint is olyan, mint egy gyilkológép - szoros barátságot köt. Ez a barátság azonban csak tiszavirág életű: a sors a barátokat ellentétes oldalra sodorja és elkerülhetetlennek látszik, hogy egy nap szembe kerüljenek egymással. És akkor valakinek meg kell halnia ');
INSERT INTO movie_detail VALUES('10KR004', 'Taxisofőrből lett alkalmi bérgyilkos érkezik a fővárosba a határon túlról. Mire hosszú megfigyelés után lecsapna a kiszemelt áldozatra, más fejezi be a véres munkát. Ám hősünknek kell menekülnie a rendőrség, közvetlen megbízói, illetve a szöuli maffia elől, miközben eltűnt feleségét is megkeresné ez az elfoglalt ember. ');
INSERT INTO movie_detail VALUES('10KR005', 'Eun Yi a középkorú elvált nő egy gazdag családnál vállal munkát szobalányként/dadaként. Hamarosan a ház ura Hoon kihasználja a köztük lévő társadalmi különbségből adódó előnyös helyzetét és ágyba bújik vele. Hoon "látogatásai" egyre gyakoribbak lesznek, és Byung Shik az idős házvezetőnő jelenti a viszonyt a feleség anyjának, Mi Hee-nek. Eun Yi hamarosan teherbe esik, erre rájönnek a család nőtagjai is és Hae Ra, a feleség és az anyja abortuszra akarják kényszeríteni, de a nő meg akarja tartani a gyereket és el akarja hagyni a házat. Hae Ra mesterkedésének köszönhetően Eun Yi elveszíti a gyereket, amitől teljesen összeomlik és úgy dönt saját kezébe veszi a dolgok irányítását. ');
INSERT INTO movie_detail VALUES('14KR003', 'Yeon-shim egy siratóasszony lányaként olyan alacsony sorból származik, hogy még a társadalmi ranglétra alján álló kiszengek közé sem akarják beválogatni. Ő azonban hajthatatlan, mert inkább árulná a mosolyát, mint anyja nyomdokain haladva a sírását.
Yoon-soo egy nemesember fia, akit kiszeng anyja miatt lenéznek és megvetnek apja előkelő családjában. Az ifjú és a leány sorsszerű találkozása mindkettejük életét megváltoztatja.');
INSERT INTO movie_detail VALUES('14KR004', 'Cso Dolszok 30 éve készít hanbokot, a királyi szabóság, a Szangivon főszabója. Amikor a királyné varrónői véletlenül tönkreteszik a király ceremoniális öltözetét, az egyik hivatalnok bemutatja a királynénak I Gongdzsint, egy tehetséges, szabályokkal nem törődő, korát megelőző ötletekkel rendelkező fiatal szabót, aki vállalja az öltözet felújítását. A darab kiválóan sikerül, a királyt lenyűgözi a fiatalember tehetsége. Gongdzsin így az udvari szabóságba kerül, és forradalmi dizájnjaival, elképesztően gyönyörű női hanbokjaival felforgatja a palota és a város életét. A fiatalember első látásra beleszeret a férje által elhanyagolt királynéba, akinek lélegzetelállító összeállításokat készít. Csóban egyre nő a düh és elkeseredettség, ahogy a fiatal, lángelme ruhatervező lassanként elhódítja tőle a megrendelőket, beleértve a királyt is, pont amikor végre, 30 év szolgálat után nemesi rangot kaphatna. Amikor a király kiszemeli magának a főminiszter lányát, a két szabó olyan udvari intrikába kerül, mely végül tragédiához vezet. ');
INSERT INTO movie_detail VALUES('15KR002', 'Hwan Hui a leghíresebb mágus Murangru piros lámpás negyedében, Uijiben. Gyerekkorában szexuálisan bántalmazta Gwi Mol, egy bűvész a Csing-dinasztiából. Azonban a fiúnak és barátjának, Bo Eumnek sikerült elszöknie tőle, de a mai napig félnek, hogy a férfi végül rájuk talál és ez megkeseríti életüket.
Eközben, Cheong Myungnak a Csoszun-dinasztia hercegnőjének Csingbe kell utaznia, hogy feleségül menjen az ottani herceghez. Nem akar megházasodni, de nem szállhat szembe családjával. A Csingbe vezető úton megállnak Uijiben. A hercegnő itt találkozik először Hwan Huivel épp akkor, amikor le akarja vetni magát a szirtől. Hwan Hui nem tudja, hogy a lány a hercegnő és beleszeret. Cheong Myung szintén beleszeret a fiúba. Szerelmük azonban teljesedhet ki, mivel visszatér Csoszunba a kegyetlen Gwi Mol, aki még mindig Hwan Huit és Bo Eumot keresi és bosszúra szomjazik.');
INSERT INTO movie_detail VALUES('15KR003', 'A film a koreai háborúban játszódik, a fegyverszünet előtti 3 napban. Nam-Bok dél-koreai katona. Egyszerű gazdálkodó volt, mielőtt a hadseregbe került. Nam-Bok azt a megbízást kapja, hogy egy titkos dokumentumot adjon át egy meghatározott időben és helyen, de az észak-koreai hadsereg támadása miatt Nam-Bok elveszíti a dokumentumot. Eközben Young-Gwang egy észak-koreai katona. Ő egy tank legénység tagja. Dél felé tartva csapatát bombázzák, és ő marad az egyetlen. Már kész hazatérni, de útközben ő találja meg a dokumentumot. A két férfi a nyugati fronton találja magát egymással szemben. ');
INSERT INTO movie_detail VALUES('17CN001', 'A film története szerint egy álruhás rendőrnyomozó megpróbálja felszámolni a város drog-szindikátusát.');
INSERT INTO movie_detail VALUES('16KR005', 'Hyojong király uralkodásának idején, az 1650-es években járunk. Kína északi területén a Csing-birodalomba eladott csoszoniakat élő pajzsként használják fel a csatákban. Ebből a pokolból szökik meg In-hong, Bo-won és Gyeon. A csábos külsővel, rendkívüli merészséggel és gyors észjárással megáldott In-hongból Csoszonba hazatérve szélhámos lesz. A kövér öregember, az ártatlan képű kölyök és egy női sámán lesznek a segítői.  A "Füllentések mestere" banda kezdetben apró furfangokkal csal ki pénzt a gazdagoktól, ám idővel egyre nagyobb szabású csalásokhoz folyamodik és országos hírnévre tesz szert. Miután még a palota kincstárából is sikerül aranyat csenniük, In-hong úgy dönt, hogy a befolyásos Seong Dae-ryeon kormányzó féltve őrzött értékes dohányát fogják ellopni. A küldetés azonban balul sül el, In-hong pedig bosszút forral. Elhatározza, hogy a nagyúr megtévesztéséhez még a Daedong folyót is áruba bocsátja. ');
INSERT INTO movie_detail VALUES('11KR002', 'A történet egy komikus Baekjei történet mesél el, amiben Hwapyung hercegnő le szeretne fogyni. A hercegnő csupa szív, kedves teremtés, egyetlen problémája, hogy kicsit pufók. Az esküvője után nem sokkal rájön, hogy újdonsült férje inkább a karcsú udvarhölgye, Hongdan társaságában leli kedvét. Hwapyung hercegnőnek ez már több a soknál ezért beszél a királlyal, aki az udvarba hívat egy titokzatos férfit, akinek a segítségével talán vissza tudja hódítani a férjét.  ');
INSERT INTO movie_detail VALUES('11KR003', '. sz. 668-ban járunk. Silla a kínai Tang-birodalommal szövetkezve 8 évvel ezelőtt Pekcsét már lerohanta, most pedig Kogurjóra fáj a foga. Az ellenséges erők a kogurjói Phenjan erőd előtt gyülekeznek. A támadás azonban késik, mert a Tang vezér minimalizálni akarja serege veszteségét, Sillának pedig nem akaródzik erősítést küldenie, mert Kim Yu-sin tábornok rájön arra, hogy a Tang végső célja a Koreai-félsziget feletti teljes uralom megszerzése. A mulatságos, ironikus komédiában modern, meglehetősen trágár nyelvezettel követhetjük nyomon a csata alakulását');
INSERT INTO movie_detail VALUES('17KR004', 'Egy taxisofőr segít egy német riporternek tudósítani a Gwangju felkelésről. A filmet megtörtént események ihlették, ugyanis Jürgen Hinzpeternek valóban egy koreai taxis, Kim Sa-Bok segített 1980 májusában a közlekedésben és a tudósításban. ');
INSERT INTO movie_detail VALUES('11KR004', 'Eun Yi egy divatlap főmunkatársnője, akinek mindene a munkája, nagy ritkán szorít csak időt szüleire, barátnőire és öccsére. Pasi-ügyben olyan magasra tette a mércét, hogy régóta egyedül tengeti életét. Magányosság ellen barátnői azt javasolják, tartson valamilyen háziállatot, például egy helyes kutyust, akivel törődhet. Mielőtt azonban megérkezne az internetről rendelt, várva várt kedvenc, váratlanul beállít hozzá testvére, aki szállást kér nála, magával hozva haverját is, Kang In Ho-t. In Ho egy fiatal, tehetséges balett-táncos, akinek derékba tört karrierje, mikor táncpartnere súlyosan megsérült, azóta nem igazán találja helyét, próbál más művészeti irányokba elindulni. Eun Yi egy éjszakára befogadja őket, arra azonban nem számít, hogy öccse átveri In Ho-t, begyűjt tőle többhavi lakbért, majd lelép. Ezek után nehéz lesz kitenni az átvert fiút, aki minden eszközt megragad, hogy maradhasson, végül abba is belemegy, hogy elvállalja a háziállat szerepét. Ezek után megkezdődik humorban bővelkedő, kalandos együttélésük, s nyomon követhetjük, hogyan változik meg az egymásról kialakított véleményük. Már épp kezd alakulni is valami közöttük, amikor váratlanul felbukkan Eun Yi első szerelme, ezzel komoly dilemmát okozva a lánynak.');
INSERT INTO movie_detail VALUES('15KR004', 'A romantikus melodráma főszerepeit két gyönyörűen mutató és nagyon tehetséges színész alakítja. A női főszereplő, MOON Chae Won partnere ezúttal a mostanában „ügyeletes szívtiprónak” is kikiáltott YOO Yeon-seok. A történet bájosan indul: két fiatal utazik a Szöulból Busanba tartó KTX vonaton. A nő előéletéról egylőre annyit tudunk, hogy tíz év után szakítottak a barátjával, mert épp előtte való nap derült ki, hogy az elveszi az első szerelmét. A lány tehát sebezhető lekiállapotban van. Nem így a mellette helyet foglaló fiatalember, aki szinte perceken belül tudatja vele, hogy szívesen eltöltene vele egy éjszakát… A nő persze igyekszik kibújni, de a vonat lerobban és a Busanba tartó buszon újra egymás mellé sodródnak és a nő előtt fokozatosan feltárul egy könnyelmű pasi bőre mögé bújt, sokkal mélyebb érzésű fickó cseppet sem sebezhetetlen világa… ');
INSERT INTO movie_detail VALUES('03KR001', 'Az i. sz. VII. században a Koreai-félszigeten három királyság hadakozik egymással: Silla, Pekcse és Kogurjo. Kim Chun-chu, a sillai király a kínai Tang-birodalommal szövetkezve kíván csapást mérni a másik két királyságra. 660 nyarán Tang hajók futnak be Incheon kikötőjébe. Uija, a pekcsei király abban bízik, hogy az egyesült erők az északra fekvő Kogurjót akarják megtámadni. Silla azonban a Tanggal összefogva előbb Pekcsét szeretné meghódítani. Hwangsanbul erődjét Gye-baek tábornok vezetésével 5.000 hős pekcsei katona védelmezi Kim Yu-sin sillai tábornok 50.000 katonájával szemben. A mulatságos, ironikus komédiában modern, meglehetősen trágár nyelvezettel követhetjük nyomon a csata alakulását.

A film folytatása a A csatamező hősei (Pyeong-yang-seong) című komédia.');
INSERT INTO movie_detail VALUES('14KR005', 'Young-eun egy középiskolás lány, aki beleszeret a tornatanárába, és idővel valósággal megszállottja lesz a férfinak. Rafináltan befurakodik az otthonába, és gátlástalan viselkedésével veszélybe sodorja a tanár feleségét és a születendő kisbabájukat.');
INSERT INTO movie_detail VALUES('16KR006', 'Soo-hyun egy 50-es éveiben járó gyermeksebész, aki Kambodzsában megműt egy ajakhasadékkal született kisbabát. A vak nagyapa hálája jeléül egy 10 pirulát tartalmazó üvegcsét ad neki, mivel megtudja, hogy az orvosnak minden vágya, hogy találkozzon valakivel. Soo-hyun Koreába hazatérőben bevesz egy pirulát a repülőgépen. Legnagyobb döbbenetére 30 évvel korábban találja magát a puszani pályaudvaron, ahol rögtön ifjúkori énjébe botlik. Innentől kezdve időutazóvá válik, aki kezdetben csak látni akarja, később pedig meg is szeretné menteni állatidomár szerelmét, aki annak idején fiatalon halt meg.');
INSERT INTO movie_detail VALUES('12KR003', 'Hwa-yeon egy nagyúr lánya, aki alacsony származású szerelmével megpróbál elszökni, hogy ne kelljen a palotába mennie. A szökés nem jár sikerrel, így a lány a király felesége lesz. Szépsége azonban korábban már elbûvölte Sung-won herceget, Õfelsége féltestvérét is. 5 évvel késõbb a király gyanús körülmények között meghal. A királyné és a kis herceg helyzete ingataggá válik, mivel a gonosz anyakirályné (Sung-won édesanyja) semmilyen eszköztõl nem riad vissza, hogy megszilárdítsa a fia hatalmát. Egy mérgezési botrány kapcsán az ifjú királynak el kell döntenie, hogy a szerelmének vagy az anyjának hisz-e.');

INSERT INTO movie VALUES('2025526', '11KR005', 'Íjak háborúja', 'Choi-jong-byeong-gi hwal', '2h02min', 'Akció,Dráma,Történelmi', 2011, 'HD', 7.2, '6y95EOzHpTM', 'kr', 'hu,gb,cs', 1);
INSERT INTO movie_detail VALUES('11KR005', 'A kínai mandzsu hadak a XVII. században kétszer is megszállták Koreát. Ebben az időszakban él az ifjú Nami, aki tökéletesen képzett íjász. Szülei halála óta a családot számára egyetlen húga jelenti, akiért bármire képes lenne. Nami szarvasra vadászik az erdőben, amikor portyázó hadak elrabolják az esküvőjére készülő húgát. Hogy megmentse testvérét, egymaga száll szembe a sereggel, és számtalan harcossal végez. Ezt látva azonban a mandzsu tábornok éktelen haragra gerjed, és hajtóvadászatot indít a rejtélyes íjász után.');

INSERT INTO movie VALUES('5503266', '16KR007', 'Hazatérő lelkek', 'Gwi-hyang', '2h07min', 'Dráma,Történelmi', 2016, 'DVDRip', 7.1, 'NIQUFSJp2GI', 'kr', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('16KR007', 'A második világháború alatt koreai lányok tízezreit szakították el a családjuktól, hogy a japán birodalmi sereg katonái részére szexuális szolgáltatást nyújtsanak. Az un. komfort-állomásokon fogva tartották, rendszeresen megverték és megerőszakolták őket. Az idős Young-hee egy tévéműsor kapcsán emlékezik vissza Jung-minnal kötött barátságára. Mindketten tizenévesek voltak, amikor 1943-ban elhurcolták őket a japán katonák.');

INSERT INTO movie VALUES('2071441', '12KR004', 'Veszedelmes viszonyok', 'Wi-heom-han gyan-gye', '1h50min', 'Dráma,Misztikus,Romantikus', 2012, 'DVDRip', 5.9, 'BJpvlSZTOgY', 'kr', 'gb,hu', 1);
INSERT INTO movie_detail VALUES('12KR004', 'Sanghaj az 1930-as években, a háború árnyékában. A varázslatos és kavargó várost Kelet Párizsaként is emlegetik. Mo Jieyu, a felső tízezer korosodó tagja találkozik az egykori barátjával, a playboy Xie Yifannal. A férfi mindig szerette az asszonyt, így hagyja magát rábeszélni, hogy játszanak egy csalóka játékot. Xie Yifannak el kell csábítania, majd el kell hagynia az ártatlan és naiv Du Fenyut. A játék azonban veszélyes fordulatot vesz, amikor Xie beleszeret Duba.');

INSERT INTO movie VALUES('4914580', '16KR008', 'Árnyak ideje', 'Miljung', '2h20min', 'Akció,Dráma,Thriller', 2016, 'HD', 7.2, '7yw4Nl5TbXY', 'kr', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('16KR008', 'Titkok, hazugságok, ármány, elnyomók és elnyomottak harcának brutalitása, valamint a lelepleződés paranoid félelme itatja át Kim Jee-woon történelmi köntösbe bújtatott kémthrillerét. Rideg, szentimentalizmustól mentes hangnem, komplex karakterek és cselekmény, stílusos és elegáns rendezés. Újabb egzotikus gyöngyszem Dél-Koreából.
Lee Jung-chool a koreai tartomány politikai rendőrségének főparancsnoka, akit japán feljebbvalója Higashi azzal bíz meg, hogy derítse ki az ellenállás legújabb célpontját, férkőzzön a tagok közelébe, majd kerítse őket kézre. Egy korábbi rajtaütés során életét vesztette Lee egykori barátja Kim Jan-ok is, ami alapjaiban rengeti meg a férfi elkötelezettségét hűbéresei irányába. Jól érzékeli ezt Higashi is, aki nem bízva mindent a véletlenre melléküld egy ambiciózus fiatal tisztet, Hashimotót, akinek csak papíron feladata Jung-chool segítése, valójában azt kell figyelnie, hogy jól végzi-e a koreai a munkáját. A megrendülést a lázadó csoport vezére Che-san is ki akarja használni, és maga mellé szeretné állítani Jung-choolt.');

INSERT INTO movie VALUES('1587729', '10KR006', 'Hetvenegyen a tűz közepébe', 'Pohwa sogeuro', '2h', 'Akció,Dráma,Háborús', 2010, 'DVDRip', 7.4, 'Wh-dGMYWma4', 'kr', 'hu', 1);
INSERT INTO movie_detail VALUES('10KR006', 'Ez a dráma egy igaz eseményen alapul, mely 71 bátor tanuló történetét mutatja be. Mindannyian önkéntesek, kiképzésre nagyon nincs idő, így rögtön a mély vízbe dobják őket. Egy középiskolában táboroznak le, feladatuk, hogy megvédjék a területet az észak-koreai katonáktól. A történetet Oh Jung-Bum szemszögéből követhetjük figyelemmel, akit szinte a semmiből neveznek ki parancsnoknak. Természetesen ez a többi újoncnak nem igazán tetszik... Ők 71-en magukra maradnak, az ellenséges haderő viszont közeledik...');

INSERT INTO movie VALUES('0475616', '05KR002', 'Nyomozó', 'Hyeongsa', '1h48min', 'Akció,Vígjáték,Misztikus', 2005, 'DVDRip', 6.0, 'oX6vGV4pswY', 'kr', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('05KR002', 'A film cselekménye, évekkel ezelőtt, a Joseon-dinasztia idején játszódik. Egy fiatal Namsoon nevű rendőrt társával együtt, egy hamis gyűrűt fedeznek fel, amit bűnözők akarnak felhasználni, a gazdaság és kormány gyengítésére.
A filmnek nagyon szép a képi megjelenítése. Sokszor festményszerű, máskor teátrális, mint egy balett. Néha meglepő a kamera mozgása. Inkább egy táncelőadás benyomását keltette az egész film - sok-sok üldözéssel és kardforgatással. ');

INSERT INTO movie VALUES('0255589', '00KR002', 'A sziget', 'Seom', '1h30min', 'Dráma,Thriller', 2000, 'HD', 7.1, 'o75xBq1pHJA', 'kr', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('00KR002', 'Távol a civilizációtól létezik egy sziget, ahová egyesek azért járnak, hogy horgásszanak, mások azért, hogy szexuális vágyaikat kielégítsék. Egy Hee Jin nevű fiatal nő viszi át őket csónakján a különbözű színekben pompázó kis faházakhoz. Van, aki partnerét is magával hozza a városból, mások prostituáltakat rendelnek, és van, aki Hee Jinhez fordul. Egy nap megérkezik a szigetre Hyun Shik, az ex-rendőr. Szörnyű bűn terheli a lelkén: megölte szeretőjét. Amikor Hyuk Shik öngyilkosságot próbál elkövetni, és Hee Jin megakadályozza ebben, különös kötelék szövődik a két ember között.');

INSERT INTO movie VALUES('4900708', '16KR009', 'Creepy', 'Kurîpî: Itsuwari no rinjin', '2h10min', 'Misztikus,Thriller', 2016, 'DVDRip', 6.3, '-zrmbXhvpDg', 'jp', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('16KR009', 'Az egykori detektív, Takakura egy új házba költözik feleségével, és egy volt kollégája kérésére utánanéz a környéken egy hat évvel korábbi eltűnési ügynek. Hamarosan sejteni kezdi, hogy furcsán viselkedő szomszédjának valami köze lehet az esethez. ');

INSERT INTO movie VALUES('1155053', '08KR001', 'Egy fagyott virág', 'Ssang-hwa-jeom', '2h13min', 'Dráma,Történelmi,Romantikus', 2008, 'HD', 7.2, 'UF58iO2swWY', 'kr', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('08KR001', 'Hamisítatlan királydráma, annak minden kellékével. Ami hiányzott a közelmúlt kosztümös koreai filmjeiből, az mind megtalálható ebben a szuperprodukcióban. Sőt, még annál is több. A film ugyanis sokkolja a korábbi filmekhez szokott közönséget - egész egyszerűen ennyi (és ráadásul ilyen nyílt) ágyjelenetet koreai közönségfilmben eddig még nem lehetett látni.');

INSERT INTO movie VALUES('1119199', '08KR002', 'Egy ember, aki Superman volt', 'Superman ieotdeon sanai', '1h42min', 'Dráma,Vígjáték', 2008, 'HD', 7.4, 'sl4UUI2Wn_g', 'kr', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('08KR002', 'Gianna Jun-ra angolosított nevet viselő színésznő ezúttal egy tévés producert játszik, akinek hétről-hétre érdekes emberekről kell szórakoztató műsorokat forgatnia. A rengeteg stresszel járó melóba persze teljesen be is savanyodik és már-már otthagyná az egészet, amikor egy önmagát Superman-nek képzelő ürge tűnik fel a színen, akivel hamarosan közvetlen kapcsolatba is kerül. A szemmel láthatóan őrült fickó mindenkin és mindenkinek segíteni akar és az a rögeszméje, hogy a fejében levő kriptonit miatt veszítette el szuperképességeit. De vajon mi is kell valójában ahhoz, hogy az ember Superman lehessen?');

INSERT INTO movie VALUES('6214734', '17KR005', 'Egy nap', 'Eoneunal', '1h58min', 'Dráma,Fantázia', 2017, 'HD', 6.5, 'LsSbjNXc6-M', 'kr', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('17KR005', 'Felesége halála után, Lee Kang Soo, a biztosítási nyomozó mély depresszióba zuhan. Új ügyet kap. Egy látássérült fiatal nő közlekedési balesetét kell kivizsgálnia. Dan Mi So autóbalesetet szenvedett és jelenleg vegetatív állapotban van. Közvetlenül a baleset után Mi So kilép a testéből és onnantól kezdve külső szemlélője az eseményeknek, mindaddig, míg a kórházban össze nem fut Kang Soo-val. A férfi ugyanis az egyetlen, aki látja és hallja őt.');

INSERT INTO movie VALUES('0363226', '03JP001', 'A szamuráj', 'Zatôichi', '1h56min', 'Akció,Vígjáték,Krimi', 2003, 'DVD', 7.6, '5ddl2zlpBa4', 'jp', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('03JP001', 'A történet XIX. századi Japánba vezet minket. Főhőse Zatoichi, látszatra csupán egy vak vándor, aki szerencsejátékból és masszírozásból él. De az álarc mögött valójában egy kardforgató mester rejtőzik, megáldva a lélegzetelállítóan pontos szúrások és a villámgyors kardrántás tehetségével. Zatoichi vándorlása során egy eldugott kis hegyi városkába ér, melyet Ginzo bandája tart hatalmában.');

INSERT INTO movie VALUES('4922946', '15KR005', 'Elveszett virág', 'Eo Woo-dong', '1h41min', 'Dráma,Romantikus', 2015, 'HD', 5.8, 'WlJp2px8nQM', 'kr', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('15KR005', 'Hye-In egy kormányhivatalnok lánya. Szép és okos. Yi-Dong a királyi család egyik tagja, aki felfigyel a lányra. Sármját kihasználva meggyőzi a lány apját, és rövid időn belül feleségül veszi Hye-In-t.
Esküvőjük után azonban Yi-Dong visszatér szoknyapecér életmódjához, és más lányokkal tölti az idejét. Egyik este találkozik Moo-Gong-gal, aki szerelmes Hye-In-be. Yi Dong féltékeny lesz, és kényszerítu Hye-In-t, hogy végignézze amint egy másik nővel szeretkezik. Hye-In, hogy bosszút állhasson, hogy ő legyen a Csoszon kor leghíresebb kiszengje, Er Woo Dong!  ');

INSERT INTO movie VALUES('3084836', '13VN001', 'Az orgyilkos hölgy', 'My nhân ke', '1h23min', 'Akció', 2013, 'DVDRip', 5.7, 'ysyy5ug2Tk4', 'vn', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('13VN001', 'Amikor az elit család elrabolt lányát megmenti egy trió, a lány lassan rájön, hogy ők igazából jól képzett bérgyilkosok, és csatlakozik hozzájuk. Egy célja van, bosszút állni azokon, akik ezt tették vele. ');

INSERT INTO movie VALUES('1499666', '09KR003', 'Számkivetett a Holdon', 'Kimssi pyoryugi', '1h56min', 'Dráma,Romantikus', 2009, 'DVDRip', 8.1, '-_Tis-5dfN4', 'kr', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('09KR003', 'Az eladósodott kisember, Kim úr öngyilkosságot kísérel meg, leveti magát Szöul egyik hídjáról, ám a megnyugvást hozó mennyország helyett egy lakatlan szigeten ébred. A folyóparti lakások egyikében él egy lány, aki már három éve nem mozdult ki az otthonából... ');

INSERT INTO movie VALUES('5066556', '15KR006', 'Egy öreg vadász meséje', 'Daeho', '2h19min', 'Akció,Kaland,Történelmi', 2015, 'HD', 7.3, 'hjt4GnoCZ40', 'kr', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('15KR006', 'A látványos jelenetekben bővelkedő film egy híres vadász és egy legendás tigris misztikus kapcsolatát meséli el. 1915-ben Man-duk békésen tanítgatja a kisfiát vadászni a Csiriszan-hegyen, miközben Korea már japán megszállás alatt áll.
10 évvel később gyógyfüvek gyűjtögetésével tengeti az életét, és nem hajlandó puskát fogni a kezébe, hiába parancsolják meg neki, hogy nyújtson segédkezet a Hegyek Urának tartott tigris elejtésében. A helyi vadászok vezetője végül cselhez folyamodik; megkörnyékezi Man-duk jobb életre vágyó kamasz fiát.
A délről érkezett japán kormányzó szilárdan eltökélte, hogy kiirtja az utolsó koreai tigrist is, ezért úgy dönt, hogy a tél beállta ellenére beveti még a japán tüzérséget is.');

INSERT INTO movie VALUES('1412334', '09JP001', 'A szamuráj hercegnő', 'Samurai Purinsesu: Gedô-hime', '1h22min', 'Akció,Horror', 2009, 'DVDRip', 4.5, 'BdI_z-PSf_0', 'jp', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('09JP001', 'Egyszer volt, hol nem volt, volt egyszer egy őrült tudós (Kyoraku), akinek mániája volt, hogy két rendkívül bájos segédjével az útjába akadó emberi testrészekből új lényeket, ún. mecha-kat alkosson. Főszereplőnket, a későbbi Szamuráj Hercegnőt tíz másik barátnőjével együtt megerőszakolja egy csapat rosszarcú ember, a végén pedig halomra ölik őket.');

INSERT INTO movie VALUES('5215952', '16KR011', 'Kokszongi sirató', 'Gok-seong', '2h36min', 'Fantázi,Horror,Misztikus', 2016, 'HD', 7.5, 'MQO5j8vuJGc', 'kr', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('16KR011', 'Egy idegen érkezése után nem sokkal rejtélyes betegség söpör át a kis falu lakóin. Egy rendőrnek hamarosan személyes üggyé válik a dolog, mikor a kislánya is megbetegedik, és ki kell derítenie az okokat, hogy megmentse őt. ');

INSERT INTO movie VALUES('1059200', '07KR002', 'A kiszeng költőnő élete', 'Hwang Jin-yi', '2h21min', 'Dráma,Életrajz,Történelmi', 2007, 'DVD', 6.5, '922wP3ruEiw', 'kr', 'hu', 1);
INSERT INTO movie_detail VALUES('07KR002', 'Egy arisztokrata családban nevelkedő lányról kiderül, hogy valójában csak fogadott gyerek, valódi anyja egy szolgáló. El kell hagynia a családi házat, s a nem túl rózsás lehetőségei közül a legjobbnak az tűnik, hogy beáll dolgozni egy bordélyházba. Rövid időn belül a legkeresettebb társalkodó hölgy lesz a városban, s feltűnik gyermekkori szerelme is, aki idő közben banditává avanzsált. A helyzetet bonyolítja új helytartó érkezik, aki szintén kiveti hálóját Hwang Jin-yi-re, s úgy tűnik, éppen a megfelelő utat választja a hölgy szívének elnyeréséhez…');

INSERT INTO movie VALUES('1165253', '08KR003', 'Álom', 'Bi-mong', '2h21min', 'Dráma,Fanzázia,Misztikus', 2008, 'DVD', 6.6, 'fV8aAEFfGu4', 'kr', 'hu,gb,ru', 1);
INSERT INTO movie_detail VALUES('08KR003', 'A dél-koreai sztárrendező, Kim Ki-duk 15. nagyjátékfilmjében Jin felriad egy olyan rémálomból, amelyben ő egy közlekedési balesetet okozott. Felzaklatva rögvest autóba ül és elvezet a megálmodott ütközés helyszínére, ahol kiderül, hogy valóban megtörtént az eset. Az elkövető, Ran (Lee Na-young) tagadja, hogy bármi köze lenne a balesethez, állítása szerint ugyanis ő végig aludt az otthonában. Jin rádöbben, hogy a lány alvajáróként ténylegesen véghezvisz mindent, amit ő megálmodik.');

INSERT INTO movie VALUES('2290840', '12KR005', 'A férfi aki királyt játszott', 'Gwanghae: Wangyidoen namja', '2h11min', 'Dráma,Történelmi', 2012, 'HD', 7.8, 'PAZ7wU2P_lI', 'kr', 'hu', 1);
INSERT INTO movie_detail VALUES('12KR005', 'A férfi aki királyt játszott című dél-koreai filmdrámában egy király mindent megtesz azért, hogy felkutassa hasonmását azért, hogy veszély esetén helyet cserélhessen vele, s ezzel megóvja életét. Ám a Koldus és királyfi című meséhez nagyban hasonlító történetben az uralkodó nem tanul semmit a szegények életéről és a sanyarú sorsból a trónra lépő ifjú sem lesz boldogabb a hirtelen jött csillogástól ');

INSERT INTO movie VALUES('4136696', '14KR006', 'A császárért', 'Hwangjereul wihayeo', '1h44min', 'Akció,Krimi,Thriller', 2014, 'DVD', 5.8, 'CI49FBjqkDY', 'kr', 'hu', 1);
INSERT INTO movie_detail VALUES('14KR006', 'Lee Hwan, a fiatal baseball játékost kirakják a ligából tiltott fogadások miatt. Adósságba veri magát, cserébe dolgoznia kell az uzsorásnak. Szerelem, pénz és összeesküvések...');

INSERT INTO movie VALUES('4696222', '15KR007', 'Északi határvonal', 'Yeonpyeong haejeon', '2h10min', 'Dráma,Háborús', 2015, 'HD', 6.6, 'MeoaaZASBNs', 'kr', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('15KR007', 'A Yeonpyeong második csatájaként ismert igaz történet alapján ez a film elmondja a harcban harcoló és meghalt fiatal katonák történetét. A csata 2002 június 29-én, a sárga tengeren zajlott, amikor két észak-koreai hajó felszállt az NLL-re - az északi határvonalra -, és a dél-koreai járőrhajón tüzeltek Chamsuri 357-gyel, hat embert megöltek és 18 sérültet .');

INSERT INTO movie VALUES('1275830', '08KR004', 'Sunny', 'Nim-eun-meon-go-sae', '2h06min', 'Háborús,Romantikus,Dráma', 2008, 'DVDRip', 6.5, 'rgaE87_Z0xA', 'kr', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('08KR004', 'Soon Yi egy régimódi, engedelmes lány, aki egy előre elrendezett házasság útvesztőibe csöppen, s a vidéki élet egyhangúságában egyetlen öröme az éneklés marad. Bár házassága még igen friss, rövid időn belül elszakad férjétől, aki beáll a seregbe. Ekkor Soon Yi még nem is sejti, milyen hatással lesz életére férje távozása. Habár tudja, hogy Sang Gilnek sokáig szeretője volt, amikor rákényszerül, hogy Vietnámban harcoló férje után induljon, úgy dönt, megtesz mindent, hogy a csatatéren megtalálja. Csodálatos hangjának, s összekuporgatott pénzének köszönhetően egy Saigonba tartó zenekarhoz szegődik, s kénytelen levetkőzni minden gátlását, hogy a katonákat szórakoztatva ismét találkozhasson férjével, aki azt mondta, a lány még csak azt sem tudja, mi az igaz szerelem...');

INSERT INTO movie VALUES('4235342', '14ID001', 'Az aranypálca harcosa', 'Pendekar Tongkat Emas', '1h51min', 'Akció,Dráma', 2014, 'HD', 6.3, 'ZSrxRQQCLU', 'id', 'hu,ru,gb', 1);
INSERT INTO movie_detail VALUES('14ID001', 'Cempakának , az Aranypálca Harcosnak, négy tanítványa közül kell kiválasztania, hogy ki legyen az utódja, akinek átadhatja a nem mindennapi erővel és hatalommal bíró Aranypálcát. Nem kis feladat hárul arra, aki e bizalmat megkapja Cempakától. Az Aranypálca mellett, megörökli az Aranypálca harcos címet is, és ő lesz az, aki továbbviszi a harcosok képzésével foglalkozó Aranypálca Ház hírnevét és befolyását. Ahhoz, hogy a kiszemelt, méltó utódja legyen a Gurunak, még egy dologra van szükség, meg kell tanulnia az „Aranypálca körbeöleli a földet” nevű mozdulatot, amelyet senki nem tud kivédeni. Cempaka összehívja tanítványait. Elmondja nekik, hogy eljött az idő, hamarosan megnevezi az örökösét, és a kiválasztottjával elvonul a hegyekbe, hogy a végső mozdulatra megtanítsa. Mindenki tisztában van vele, hogy csakis Biru veheti át a Guru helyét, hiszen ő a legidősebb és a legképzettebb harcos közöttük. Ám Cempaka Darát választja ki e nemes feladatra, ami egyáltalán nem tetszik Birunak…');

INSERT INTO movie VALUES('0263101', '00TH001', 'Veszélyes Bangkok', 'Krungthephmh̄ānkhr xạntrāy', '1h45min', 'Akció,Krimi,Romantikus', 2000, 'DVDRip', 6.6, 'vUzy3G1wMG8', 'th', 'hu', 1);
INSERT INTO movie_detail VALUES('00TH001', 'A történet egy süketnéma bérgyilkosról és a partneréről szól Bangkokban. A bérgyilks partnerének barátnője sztriptíztáncosnő egy helyi klubnál. A film abba enged betekintés hogyan és milyem módon mászta meg a páros az alvilág ranglétráját, és alakította ki "gyilkosságbizniszét". Valamint azt is megtudhatjuk hogyan "keveredett" a csapatba a sztriptíztáncosnő is. Egy tragikus esemény arra készteti a bérgyilost, hogy rájöjjön, jó embereket tettek tönkre a tettei.');

INSERT INTO movie VALUES('2082180', '11KR006', 'Csak te, mindörökké', 'O-jik geu-dae-man ', '1h48min', 'Akció,Dráma,Romantikus', 2011, 'HD', 7.8, 'Iygr9zqEDPo', 'kr', 'hu', 1);
INSERT INTO movie_detail VALUES('11KR006', 'A film Jang Marcelino ex boxer és Jung-Hwa, egy vak lány történetét mutatja be. Jang múltja nagyon sötét és titokzatos, tehetséges boxoló volt, azonban egy rossz meccs után visszavonult és évekig senki nem hallott róla. Jung-Hwa egy balesetben, amiben szülei életüket vesztették, ő elvesztette látását. Azóta call centeres operátorként dolgozik, próbál valahogy megélni. Munka után minden nap egy férfivel találkozik, aki a munkahelyén a portán dolgozik. Együtt néznek a tv-ben drámákat…a férfi nem más, mint Jang Marcelino. Kissé nehezen kezeli, hogy a lány vak, ám mégis elég közel kerülnek egymáshoz, mindkettejükben kialakul valami a másik iránt. Jung-Hwa nagyon őszinte és nyílt, próbál minél többet megtudni a férfiról, de ő nagyon zárkózott.');

INSERT INTO movie VALUES('3469592', '14CN001', 'A legenda felemelkedése', 'Huang feihong zhi yingxiong you meng', '2h11min', 'Akció,Életrajz,Dráma', 2014, 'DVD', 6.6, 'yug4GaTsxS4', 'cn', 'hu', 1);
INSERT INTO movie_detail VALUES('14CN001', 'Egy árva fiú bosszút esküszik a nevelő apja haláláért és beférkőzik az alvilág soraiba. Egy olyan pokolba csöppen, ahol az ópium az úr és ahonnan nincs kiút. Egyetlen cél vezérli: megbosszulni apja halálát és megszüntetni az alvilág uralmát a város felett bármi áron...');

INSERT INTO movie VALUES('1832381', '11KR007', 'K nyomozó és a sisakvirág titka', 'Chosun Myungtamjeong', '1h55min', 'Akció,Vígjáték,Krimi', 2011, 'HD', 6.4, 'bK4wXWlZxpM', 'kr', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('11KR007', 'A régi korban játszódó fimben a címszereplőt, egy hivatalnokot titkos nyomozással bíz meg az uralkodó, hogy egy sikkasztással kapcsolatos bűnsorozatot leplezzen le. Számtalan gyilkosság történik, ahogy a gyilkos próbálja elhallgattatni a tanúkat, rendszerint sisakvirág-kivonattal, ami mérgező.');

INSERT INTO movie VALUES('3501416', '15KR008', 'A bérgyilkosság', 'Amsal', '2h20min', 'Akció,Dráma,Thriller', 2015, 'DVD', 7.3, 'vuLffAVWkXQ', 'kr', 'hu,gb', 1);
INSERT INTO movie_detail VALUES('15KR008', 'Mesterlövészekből, zsoldosokból és kettős ügynökből álló csapat lázadó azt tervezi, hogy rajtaüt a hadsereg parancsnokán a japánok által megszállt Koreában, azonban az egyetlen, aki véghez tudná vinni a merényletet, börtönben ül. A lázadók megszöktetik őt a fogságból, azonban áruló van a soraik között...');

